ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.eventcreator.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/eventcreator"
    url = ${?DB_URL}
    user = "eventuser"
    user = ${?DB_USER}
    password = "eventpass"
    password = ${?DB_PASSWORD}
}
